# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e07084a88e5bfe8f4a83c3be6b1bdf7f213f2aa2ecd1807c68def7730fed29cd2336c413afe1cd8cd406b18a791943859e3eff1b302f08b9a1394ea1ac6f7d4

test:
  secret_key_base: 75d2bcd0b56832c69a8d465b4556e5a713f7bfde593dad55a4e0961987a830ad894ed1be1f8139082a7291fd18b095f63c383d755e2c0a9198318594a8d462cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
